# steps:
# - name: 'gcr.io/cloud-builders/npm'
#   entrypoint: 'node'
#   args: ['--version']

# example deployment to cloud run
# https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run
# steps:
# # Build the container image
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/PROJECT_ID/IMAGE', '.']
# # Push the container image to Container Registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/PROJECT_ID/IMAGE']
# # Deploy container image to Cloud Run
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args: ['run', 'deploy', 'SERVICE-NAME', '--image', 'gcr.io/PROJECT_ID/IMAGE', '--region', 'REGION']
# images:
# - gcr.io/PROJECT_ID/IMAGE


steps:

 
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/portfolio:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/portfolio:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'portfolio'
   - '--image'
   - 'gcr.io/$PROJECT_ID/portfolio:$COMMIT_SHA'
   - '--region'
   - 'REGION'
images:
 - 'gcr.io/$PROJECT_ID/portfolio:$COMMIT_SHA'